--Question 1 
SELECT AVG(POWER) as AVG_POWER, MAX(POWER) as MAX_POWER , MIN(POWER) as MIN_POWER
FROM stand_user;
--Question 2
SELECT COUNT(DISTINCT PRECISION), COUNT(*)
FROM stand_user
WHERE USER_ID is NOT NULL;
--Question 3
SELECT TO_CHAR(STDDEV(POWER), '999.999') AS STDDEV_POWER, TO_CHAR(VARIANCE(POWER), '99999.999') AS VARIANCE_POWER
FROM stand_user;
--Question 4
SELECT PRECISION, AVG(POWER) AS AVG_POWER
FROM stand_user
WHERE PRECISION is NOT NULL
GROUP BY PRECISION;
--Question 5
SELECT PRECISION, AVG(POWER) AS AVG_POWER
FROM stand_user
WHERE PRECISION is NOT NULL
GROUP BY PRECISION
HAVING AVG(POWER) > 80;
--Question 6
SELECT 
  USER_NAME,
  STAND_NAME,
  POWER - (SELECT AVG(POWER) FROM stand_user) AS DIFF_FROM_AVG
FROM stand_user
GROUP BY USER_NAME, STAND_NAME, POWER;
-- Question 7 
SELECT ROUND(AVG(POWER),2) as ROUNDED_AVG_POWER
FROM stand_user;
-- Question 8
SELECT PRECISION, SUM(POWER) AS TOTAL_POWER 
FROM STAND_USER
GROUP BY ROLLUP(PRECISION);
--Question 9 
SELECT EXTRACT(YEAR FROM debut_date) AS debut_year, precision, SUM(power) AS total_power
FROM stand_user
GROUP BY CUBE(EXTRACT(YEAR FROM debut_date), precision)
ORDER BY debut_year, precision;
